#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname $0)/.."

echo "Installing Dpendencies"

echo "Installing CoPilot CLI"
curl -Lo copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux \
    && chmod +x copilot \
    && sudo mv copilot /usr/local/bin/copilot \
    && copilot version

# echo "Installing AWS CLI"
# curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
#     && unzip awscliv2.zip \
#     && sudo ./aws/install

# echo "Validating Installation of AWS CLI"
# aws --version

# echo "Installing Java 17"
# apt-get update -y \
#     && apt-get upgrade -y \
#     && apt install openjdk-17-jdk openjdk-17-jre

# echo "Cleaning up AWS CLI"
#     && rm -rf aws/ \
#     && rm -f awscliv2.zip

# echo "Installing Docker"
# sudo apt-get update \
#     && sudo apt-get install ca-certificates curl \
#     && sudo install -m 0755 -d /etc/apt/keyrings \
#     && sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc \
#     && sudo chmod a+r /etc/apt/keyrings/docker.asc

# # Add the repository to Apt sources:
# echo \
#   "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
#   $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
#   sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
# sudo apt-get update
# sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin